easy_admin:
  entities:
    Animation:
      class: App\Entity\Animation
      #tree: true
      label: 'Animation'
      list:
        # template: 'templates/easy_admin/list.html.twig'
        #sort: ['lft', 'ASC']
        # actions: 
        #   - { name: 'moveUp', icon: 'arrow-circle-up' }
        #   - { name: 'moveDown', icon: 'arrow-circle-down' }
        fields:
          - id
          - name
          - title
          - { property: 'status',  type: 'toggle' }
      form:
        fields:
          - { property: 'status', css_class: 'large', type: 'choice', type_options: { choices: { 'Offline': 0, 'Online': 1 } } }
          - { type: 'divider' }
          - { property: 'startDt', css_class: 'large', type: 'datetime' }
          - { property: 'endDt', css_class: 'large', type: 'datetime' }
          - { type: 'divider' }
          - { property: 'name', css_class: 'large', type_options: { disabled: true } }
          - { property: 'aboveTitle', css_class: 'large' }
          - { property: 'title', css_class: 'large' }
          - { property: 'subTitle', css_class: 'large' }
          - { property: 'shortText', css_class: 'awesome-ckeditor', type: 'textarea' }
          - { property: 'mainText', css_class: 'awesome-ckeditor', type: 'textarea' }
          - { type: 'divider' }
          - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType' }}
          - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
          - { type: 'divider' }
          - { property: 'tagList', css_class: 'large', label: 'Tag list' }
