easy_admin:
  entities:
    MuscleGroup:
      class: App\Entity\MuscleGroup
      label: 'Muscle Group'
      list:
        fields:
          - id
          - name
      form:
        fields:
          - { property: 'name', css_class: 'large' }
          - { type: 'group', columns: 4, label: 'Image', help: 'Pick the image to represent the muscle group' }
          - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
          - { type: 'group', columns: 4, label: 'Muscles', help: 'Pick the muscles that belong to this muscle group' }
          - { property: 'muscles', css_class: 'large', label: 'Muscles' }

