easy_admin:
  entities:
    Tag:
      class: App\Entity\Tag
      #tree: true
      label: 'Tags'
      list:
        # template: 'templates/easy_admin/list.html.twig'
        sort: ['defaultFilter', 'ASC']
        # actions: 
        #   - { name: 'moveUp', icon: 'arrow-circle-up' }
        #   - { name: 'moveDown', icon: 'arrow-circle-down' }
        fields:
          - id
          - defaultFilter
          - name
          - title
          - label
      form:
        fields:
          - { property: 'title', css_class: 'large' }
          - { property: 'label', css_class: 'large' }
          - { property: 'defaultFilter', css_class: 'large' }

